### ISSUE TITLE
this not highlighted inside brackets

### ISSUE THREAD

**Issue by michaeljs1990** [google/codemirror-mode-jsonnet#1]
```jsonnet
local first = "hello";

{
  second: "world",
  out: "%s %s!" % [first, this.second],
}
```

For this example I would expect this to be highlighted the same as if it was not inside [].

Just adding a ticket for this I'll try to take a look at it later.

**Comment by sparkprime** [comment]
It's because it's `self` not `this` :)

**Comment by michaeljs1990** [comment]
doh. thanks!
